language: java
jdk:
- oraclejdk8
- openjdk7
cache:
  directories:
  - "$HOME/.m2"
script:
- "./mvnw --batch-mode test"
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && [[ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]] && mvn deploy --settings travissettings.xml -DskipTests=true -B'
env:
  global:
  - SONATYPE_USERNAME=ahus1
  - secure: cYn4GpSuIbJOzBbywECxtbtH+3q3zvN7wNkXbY1YXK3NFxWPC3ESMt53pbi6tK1+3Qk/V7eioztzivPgiKYgHvRVKc1lMJoqmeiOBdMVpb/LfGpdkq/NaCKs4Syexipq+TNxzmAEmUnghx8C7M8QqsFjWuV1bsZSqM57aSogdU0=
