language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
script:
- "./mvnw --batch-mode test"
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && mvn deploy --settings travissettings.xml -DskipTests=true -B'
env:
  global:
  - SONATYPE_USERNAME=ahus1
  - secure: RP43FIc3Y/2PgjzZBn7xv5qU9irQ/vNb3ow0v9gbYUz2nZojEllkPtAbo7GMKKlT0eyfDzn7JCYIfnxeigGEPC7RHWJN2gzHhlXTUrc8WXZ/Y4P1Q6UvdAT/HStHBnT3Dreeulu0EFBjzNHjZvJw2cFgPT3pSiY1tEZ6S5cO/ryRAownzUzPb9oduy2lcM/K7VpasDx5S+Ok4tBd9W2gsDvQ0bcVFWwbDL9Ktv1O9i/8rZdYXYZ1Ju/yZqrSftlavIe74AbgyTwJsGAGspqBg/Td2YO3Fwb7f8bPP8HhSGxoZWwkYaUkoewJym3nST0jCw2GlWSIZLd6WN2QaDVSsUZMEFxlamO7oymWZ/W0LN35ToRgH2o3Rh1PW6HIVSvrjC+9rlzGGbWkA6tEALaTseM5oPQ+j12R1mIMo9CBhkuTkXDTSrW7cc5+M89MPXlo0ZroA7CZ+bMFearW0/mouYQzMyHBV5sCyHi2MX5N0qnWPp2TJ4+rESAUPz82S2rW3TiSYAu6MyRMHwpUHRAfGuvinL/7xFZVkYeQs91P3m80htjDG/NPRQG+H0gf0bGG/Em4TaWd2I2jwOq4vn7J0TNFEN1zXEDVfnBJ5iBqfAjgfmwdYmQxj9q51I6cc1Tbxda1wi2FapssfOgS/Z+hHJX8/WmXJQEJyuuyP4YqDEE=
